### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by csograd** [pedroj/bipartite_plots#3]
I am trying to install this package to recreate the visualizations you created here: https://pedroj.github.io/bipartite_plots/

When I run the code below to install the package, I receive the following errors.... 

withr::with_libpaths(new="C:/Program Files/R/R-3.4.3/library/", install_github("pedroj/bipartite_plots"))

* installing *source* package 'effect.lndscp' ...
** R
** preparing package for lazy loading
** help
No man pages found in package  'effect.lndscp' 
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386

     Hola PEDRO, bienvenido a R!

Error: package or namespace load failed for 'effect.lndscp' in namespaceExport(ns, exports):
 undefined exports: effectiveness, effectiveness_plot
Error: loading failed
Execution halted
*** arch - x64

     Hola PEDRO, bienvenido a R!

Error: package or namespace load failed for 'effect.lndscp' in namespaceExport(ns, exports):
 undefined exports: effectiveness, effectiveness_plot
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/R-3.4.3/library/effect.lndscp'
* restoring previous 'C:/Program Files/R/R-3.4.3/library/effect.lndscp'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by iremendoza** [comment]
I also had a bug trying to install bipartite_plots:
> devtools::install_github("pedroj/bipartite_plots")
Downloading GitHub repo pedroj/bipartite_plots@master
Skipping 15 packages ahead of CRAN: cli, coda, colorspace, digest, fansi, ggplot2, pillar, pkgconfig, R6, rlang, scales, spam, stringi, stringr, tibble
Installing 1 packages: dichromat
Installing package into ‘C:/Users/Irene/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'

**Comment by tamarahartke** [comment]
Install gave no errors for me but was not complete -- I only have functions bip_edgewt, bip_ggnet, and bip_igplot.

**Comment by pedroj** [comment]
Please use:
`devtools::install_github("pedroj/bipartite_plots")`           
`library(ggbipart)`

**Comment by pedroj** [comment]
> I also had a bug trying to install bipartite_plots:
> 
> > devtools::install_github("pedroj/bipartite_plots")
> > Downloading GitHub repo pedroj/bipartite_plots@master
> > Skipping 15 packages ahead of CRAN: cli, coda, colorspace, digest, fansi, ggplot2, pillar, pkgconfig, R6, rlang, scales, spam, stringi, stringr, tibble
> > Installing 1 packages: dichromat
> > Installing package into ‘C:/Users/Irene/Documents/R/win-library/3.5’
> > (as ‘lib’ is unspecified)
> > Error: (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
> > cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'

This seems an error unrelated to the install of `ggbipart`. Have you got the error also installing other GitHub-based packages?

**Comment by pedroj** [comment]
I'll leave te issue open for now, awaiting for any additional install bugs. I've fixed the error when trying to install package `ggnet`, now calling for installing `GGally`, which includes it.

**Comment by dkholo** [comment]
I was not able to install the package.
I am getting  devtools::install_github("pedroj/bipartite_plots")
Downloading GitHub repo pedroj/bipartite_plots@master
from URL https://api.github.com/repos/pedroj/bipartite_plots/zipball/master
Installing ggbipart
Installing 1 package: igraph
Installing package into ‘C:/Users/dkholo/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/igraph_1.2.4.1.zip'
Content type 'application/zip' length 8327030 bytes (7.9 MB)
downloaded 7.9 MB

package ‘igraph’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\dkholo\AppData\Local\Temp\RtmpIdXEbI\downloaded_packages
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/dkholo/AppData/Local/Temp/RtmpIdXEbI/devtools5a00439a487e/pedroj-bipartite_plots-540eb03"  \
  --library="C:/Users/dkholo/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'ggbipart' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error: package or namespace load failed for 'ggplot2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'rlang'
Error : package 'ggplot2' could not be loaded
ERROR: lazy loading failed for package 'ggbipart'
* removing 'C:/Users/dkholo/Documents/R/win-library/3.4/ggbipart'
In R CMD INSTALL
Installation failed: Command failed (1)
> library(ggbipart)
Error in library(ggbipart) : there is no package called ‘ggbipart’
>

**Comment by dkholo** [comment]
I was able to address the error by installing rlang package.

**Comment by pedroj** [comment]
Dear Dimitri,

Sorry for the late response-I’m in travel in Brazil, with just sporadic access to email. Thanks ever so much for your interest in the package. I’m sorry to hear you are experiencing difficulties in installing it.

The problem seems not related to the package itself but to your R installation and specifically to the ggplot2 install, which has a dependency with the rlang package and this seems to be the problem. Please try to re-install ggplot2 (perhaps using the tidyverse install) and let’s see if the problem is solved.

All the best,
-- Pedro
--------------------------------------------
