### ISSUE TITLE
Specific quadrant (Continental ) node placement question.

### ISSUE THREAD

**Issue by dkholo** [pedroj/bipartite_plots#5]
HI Pedro,
I wanted to express my appreciation of  your work. This solution can help the researchers of different disciplines.
I would greatly value your advice on how to overlay ggpipart network over a map of the world.
I am notable to formulate parameters for the network that would place specific nodes at the specific parts of the screen. Your pollination experiment would also benefit from continental positioning of the species. This would enable you to show cross continental links.
Could you help me to form a network that would position nodes in specific places of the network?
 Dmitry

**Comment by pedroj** [comment]
Thank you for the nice words, Dimitri. 
The coordinates can be generated (e.g., from GPS data) and used to place the nodes at specific positions. Function `bip_railway` uses that to plot the traditional bipartite arrangement by specifying `mode= mylayout`, where `mylayout` is a matrix where you have saved the coordinates.

For example I used that approach in `bip_railway` function:
```
# Coords for mode "A"
        coordP<- cbind(rep(2,dim(mymat)[1]), seq(1, dim(mymat)[1])+2)
# Coords for mode "P"
        coordA<- cbind(rep(4,dim(mymat)[2]), seq(1, dim(mymat)[2])+2)
# Saving coordinates as a layout
        mylayout<- as.matrix(rbind(coordP, coordA))
#
# Using something like the above code you may include any coordinate set in `mylayout` and use this
# to plot the network.
#
# Initialize and plot the network with the layout.
        test.net<- bip_init_network(mymat)
        p<- ggnet::ggnet2(test.net, mode=mylayout, label=label,
                                         size= nodesize, label.size=nodesize/3,
                                         layout.exp=1.5)
```
Another option is to use the [`popgraph`](https://github.com/dyerlab/popgraph/tree/master/R) package by [Rodney Dyer](https://github.com/dyerlab/popgraph). It's for population genetics but you may customize some of its functions to suit your needs.

**Comment by dkholo** [comment]
Thank you, Pedro. I am going to attempt using the proposed method.
