### ISSUE TITLE
Unable to run the sample code

### ISSUE THREAD

**Issue by dkholo** [pedroj/bipartite_plots#6]
I am trying to execute the sample code, but it does run properly.
Am I missing some environmentally specific items?

> bip= data.frame(P1= c(1, 12, 6, 0),
+                 P2= c(1, 0, 4, 0),
+                 P3= c(1, 7, 3, 12),
+                 row.names= letters[1:4])
> col= c("A"= "grey80", "P"= "gold2")
> bip.net<- bip_init_network(as.matrix(bip))
Error in bip_init_network(as.matrix(bip)) : 
  could not find function "bip_init_network"
> 
> bip_ggnet(bip.net, as.matrix(bip),
+           #  color= "mode", palette = col,
+           edge.label = "weights",
+           label= TRUE)
Error in bip_ggnet(bip.net, as.matrix(bip), edge.label = "weights", label = TRUE) : 
  could not find function "bip_ggnet"
> 

This code block is also not working.
Do I need to create a file manually?
> #————————————————————————————————————————————————————————————————
> # Plot layout coordinates for railway network plot. Input is the 
> # adjacency matrix.
> # 
> mymat <- read.delim("./data-raw/data.txt", row.names=1)   # Not run.
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './data-raw/data.txt': No such file or directory
> g<- bip_railway(mymat, label=T)
Error in bip_railway(mymat, label = T) : 
  could not find function "bip_railway"
> ## Loading required package: scales
> g+ coord_flip()
Error in eval(`_inherit`, env, NULL) : object 'ScalesList' not found

**Comment by pedroj** [comment]
Please reinstall the package. I've fixed the NAMESPACE file, given that several functions were not correctly exported. 
If the problem persists you may source the functions in the R folder by hand- this should be just a quick solution while the problem is fixed.
Thank you very much for your comments.

**Comment by pedroj** [comment]
I'll keep the issue open to track any additional problems.
